
-- RETAIL SALES DATA ANALYSIS


--  Objective:
-- Analyze retail sales data using SQL to uncover insights
-- related to customer behavior, product performance,
-- sales trends, revenue generation and employee performance.

-- Tools Used:
-- SQL
-- MySQL Workbench

-- Analysis :
-- 1. Customer Analysis
-- 2. Product & Category Performance
-- 3. Sales 
-- 4. Revenue 
-- 5. Employee Performance 
-- 6. Trend 


-- 1. BASIC DATA EXPLORATION

-- 1. Retrieve all records from the product table
select * from product;

-- 2. Display product names and unit prices for products costing more than 50
select productName,unitPrice from product
where unitPrice > 50;

-- 3. List all customers located in Germany
select * from customer
where country = 'Germany';

-- 2. SQl FUNTIONS AGGREGATIONS

-- 1. Calculate the total numbers of orders placed
select count(*) from orderdetail;

-- 2. Find the avg unit price of all products
select ceil(avg(unitPrice)) from orderdetail;

-- 3. Determine the total revenue generated 
select sum(unitPrice*quantity*(1-discount)) as Revenue from orderdetail;

-- 3. JOIN OPERATIONS

-- 1. Product Category Analysis
-- Display:                     Tables involved:
-- ● Product Name               ● Product
-- ● Category Name              ● Category
-- ● Unit Price

select p.productName,c.categoryName,p.unitPrice
from product p join category c 
on p.categoryId = c.categoryId ;

-- 2. Customer Order Analysis
-- Display:                     -- Tables involved:
-- ● Customer Company Name         ● Customer
-- ● Order ID                      ● SalesOrder
-- ● Order Date

select c.companyName,s.orderId,s.orderDate
from customer c join salesorder s 
on c.custId = s.custId;

-- 3. Sales Performance by Employee
-- Display:               -- Tables involved
-- ● Employee Name           ● Employee
-- ● Order ID                ● SalesOrder
-- ● Customer Name           ● Customer

select concat(e.firstname,' ',e.lastname) as EmployeeName,s.orderId,replace(c.contactName,',','') as customerName
from employee e join salesorder s 
on e.employeeId = s.employeeId
join customer c 
on c.custId = s.custId;


-- 4.  SUBQUERIES

-- 1. Find products whose unit price is higher than the average price of all products.

select productName,unitPrice,(select avg(unitPrice) from product) as avg
from product
where unitPrice > (select avg(unitPrice) from product);

-- 2. Retrieve customers who have placed more than 5 orders.

select replace(contactName,',','') as customerName
from customer
where custId in (select custId from salesorder 
group by custId
having count(custId) > 5) ; 


-- 3. Identify products that have never been ordered.

select productName from product
where productID  not in (select productId from orderdetail);

-- 5. WINDOWS FUNCTIONS

-- 1. Rank Products by Price
-- Rank products based on their unit price within each category.

select * from product;
select * from category;

select c.categoryName,p.productName,p.unitPrice,
dense_rank() over (partition by c.categoryName order by p.unitPrice desc) as rnk
from product p join category c 
on p.categoryId = c.categoryId;

-- 2. Running Total of Sales
-- Calculate the running total of revenue by order date

-- Expected columns:
-- ● Order Date  ● Order Revenue  ● Running Total Revenue

select * from salesorder;

select s.orderDate,sum(o.unitPrice*o.quantity*(1-o.discount)) as Revenue,
sum(sum(o.unitPrice*o.quantity*(1-o.discount))) over (order by s.orderDate ) as Running_total
from orderdetail o join salesorder s 
on o.orderId = s.orderId
group by s.orderDate;

-- 3. Top Customers by Revenue
-- Calculate total revenue generated by each customer and assign a rank.
-- Expected output:
-- ● Customer Name  ● Total Revenue  ● Customer rank

select * from customer;
select * from orderdetail;

select customerName,Revenue,
dense_rank() over (order by Revenue desc) as rnk
from 
(select replace(c.contactName,',','') as customerName,
sum(o.unitPrice*o.quantity*(1-o.discount)) as Revenue
from customer c join salesorder s 
on c.custId = s.custId
join orderdetail o 
on o.orderId = s.orderId
group by customerName) a;

-- 6. ADVANCED ANALYTICAL QUERIES
-- Write SQL queries to answer the following business questions:
-- 1. Which product category generates the highest revenue?

select c.categoryName,sum(o.unitPrice*o.quantity*(1-o.discount)) as Revenue
from category c join product p
on c.categoryId = p.categoryId
join orderdetail o
on p.productId = o.ProductId
group by c.categoryName
order by Revenue desc;
    
-- 2. Which customer has placed the most orders?

select * from customer;
select * from salesorder;

select replace(c.contactName,',','') as customerName,count(orderId) as totalOrders
from customer c join salesorder s 
on c.custId=s.custId
group by c.contactName
order by totalOrders desc limit 1;

-- 3. Which employee handles the highest number of orders?

select * from employee;

select concat(e.firstname,' ',e.lastname) as employeeName,count(s.orderId) as totalOrders
from employee e join salesorder s 
on e.employeeId=s.employeeId
group by e.employeeId
order by totalOrders desc;

----- Core Insights

-- 1. Beverages generated the highest revenue among all categories.

-- 2. A small group of customers contributed significantly
--    to total sales revenue.

-- 3. Some products showed no sales activity and may require
--    inventory or marketing review.

-- 4. Revenue demonstrated a positive growth trend over time.

-- 5. Employee sales performance varied across the organization.





